[package]
name = "mixrs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
pulse = { version = "2.0", package = "libpulse-binding" }
tokio = { version = "1.38.0", features = ["full"] }
